name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        task: [type-check, biome]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run TypeScript type check
        if: matrix.task == 'type-check'
        run: bun run compile
      
      - name: Run Biome
        if: matrix.task == 'biome'
        run: bun run check